name: Automation Testing with JMeter

on:
  workflow_dispatch:   # Allows manual triggering
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours at minute 0 (UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOLR_USER: ${{ secrets.solr_user }}
      SOLR_PASSWD: ${{ secrets.solr_passwd }}
      JMETER_HOME: /usr/share/jmeter
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JMeter and dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk wget libcanberra-gtk3-module
          java -version

          # Install JMeter base packages (required to setup folders)
          sudo apt install -y jmeter

          # Fix permissions so current user can modify /usr/share/jmeter
          sudo chown -R $USER:$USER $JMETER_HOME
          sudo chmod -R a+rX $JMETER_HOME

          # Download and extract Apache JMeter 5.6.3 binaries into /usr/share/jmeter
          wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz -O apache-jmeter-5.6.3.tgz
          tar --strip-components=1 -xvzf apache-jmeter-5.6.3.tgz -C $JMETER_HOME

          # Download Plugins Manager jar into JMeter lib/ext directory
          wget -O $JMETER_HOME/lib/ext/plugins-manager.jar https://jmeter-plugins.org/get
          chmod a+r $JMETER_HOME/lib/ext/plugins-manager.jar

          # Verify JMeter installation
          $JMETER_HOME/bin/jmeter --version

          echo "Installation complete. Plugins Manager ready."

      - name: Install required plugins
        run: |
          REQUIRED_PLUGINS=("jpgc-functions" "jpgc-dummy")

          # Download cmdrunner which is required by Plugins Manager CLI
          wget -O $JMETER_HOME/lib/cmdrunner-2.3.jar https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.3/cmdrunner-2.3.jar

          # Extract the PluginsManagerCMD.sh script from the jar
          java -cp $JMETER_HOME/lib/ext/plugins-manager.jar org.jmeterplugins.repository.PluginManagerCMDInstaller

          # Define a helper function to check if plugin is installed
          function is_plugin_installed() {
            local plugin_id="$1"

            if [ -z "$JMETER_HOME" ]; then
              echo "Error: JMETER_HOME is not set" >&2
              return 1
            fi

            if [ ! -f "$JMETER_HOME/bin/PluginsManagerCMD.sh" ]; then
              echo "Error: PluginsManagerCMD.sh not found in $JMETER_HOME/bin" >&2
              return 1
            fi

            if "$JMETER_HOME/bin/PluginsManagerCMD.sh" status 2>/dev/null | grep -q "$plugin_id"; then
              return 0
            else
              return 1
            fi
          }

          # Install plugins if missing
          for plugin in "${REQUIRED_PLUGINS[@]}"; do
            if is_plugin_installed "$plugin"; then
              echo "Plugin $plugin is already installed."
            else
              echo "Plugin $plugin not found. Installing..."
              $JMETER_HOME/bin/PluginsManagerCMD.sh install "$plugin"
            fi
          done

      - name: Run JMeter tests
        run: |
          # Run tests with secrets and properties passed
          $JMETER_HOME/bin/jmeter -n -t get_all_urls.jmx -Juser=$SOLR_USER -Jpasswd=$SOLR_PASSWD
          $JMETER_HOME/bin/jmeter -n -t gremove_404s.jmx

          # Cleanup potentially generated files
          rm -f jmeter.log input.csv

