name: Automation Testing with JMeter
on:
  workflow_dispatch:   # Allows manual triggering of the workflow
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours at minute 0 (UTC)
 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOLR_USER: ${{ secrets.solr_user }}
      SOLR_PASSWD: ${{ secrets.solr_passwd }}
    steps:
      - uses: actions/checkout@v3
      - name: install JMeter
        run: |
         sudo apt update
         sudo apt install -y openjdk-11-jdk
         java -version
         sudo apt install -y jmeter
         sudo apt install -y libcanberra-gtk3-module
         sudo chown -R $USER:$USER /usr/share/jmeter
         sudo chmod -R a+rX /usr/share/jmeter
         wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
         tar --strip-components=1 -xvzf apache-jmeter-5.6.3.tgz -C /usr/share/jmeter
         wget -O /usr/share/jmeter/lib/ext/plugins-manager.jar https://jmeter-plugins.org/get
         chmod a+r /usr/share/jmeter/lib/ext/plugins-manager.jar
         jmeter --version
         echo "Installation complete. Run JMeter as your user with: jmeter"
         echo "Since you own /usr/share/jmeter, Plugins Manager can now install plugins properly."
      - name: install plugins
        run: |
         REQUIRED_PLUGINS=("jpgc-functions,jpgc-dummy")
          wget -O $JMETER_HOME/lib/cmdrunner-2.2.jar https://search.maven.org/remotecontent?filepath=kg/apc/cmdrunner/2.2/cmdrunner-2.2.jar
          java -cp $JMETER_HOME/lib/ext/plugins-manager.jar org.jmeterplugins.repository.PluginManagerCMDInstaller

         function is_plugin_installed() {
          local plugin_id="$1"
          if [ -z "$JMETER_HOME" ]; then
                  echo "Error: JMETER_HOME is not set" >&2
          return 1
          fi
    
          # Verify PluginsManagerCMD.sh exists
           if [ ! -f "$JMETER_HOME/bin/PluginsManagerCMD.sh" ]; then
            echo "Error: PluginsManagerCMD.sh not found in $JMETER_HOME/bin" >&2
            return 1
           fi
    
           # Use status command to check for plugin
           if "$JMETER_HOME/bin/PluginsManagerCMD.sh" status 2>/dev/null | grep -q "$plugin_id"; then
              return 0
           else
             return 1
           fi
                                      }
  

         for plugin in "${REQUIRED_PLUGINS[@]}"; do
         if is_plugin_installed "$plugin"; then
          echo "Plugin $plugin is already installed."
         else
          echo "Plugin $plugin not found. Installing..."
          $JMETER_HOME/bin/PluginsManagerCMD.sh install "$plugin"
         fi
         done
      - name: run local files
        run: |
         jmeter -n -t get_all_urls.jmx -Juser=$SOLR_USER -Jpasswd=$SOLR_PASSWD
         jmeter -n -t gremove_404s.jmx 
         rm jmeter.log 
         rm input.csv
