name: Automation Testing with JMeter
on:
  workflow_dispatch:   # Allows manual triggering of the workflow
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours at minute 0 (UTC)
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run jmeter on github action
        uses: sebiboga/run-jmeter-github-action@main
